// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVUk3UrAAqTLhVEiCmGe4NvCeDOuoXj50',
    appId: '1:141560742872:web:45b84501c8e7d9e41228ad',
    messagingSenderId: '141560742872',
    projectId: 'hivemind-9a13f',
    authDomain: 'hivemind-9a13f.firebaseapp.com',
    storageBucket: 'hivemind-9a13f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmu5LY11_LLJtlnNlkEaHASdda0JiDZlE',
    appId: '1:141560742872:android:8d7fe39cfac7a9891228ad',
    messagingSenderId: '141560742872',
    projectId: 'hivemind-9a13f',
    storageBucket: 'hivemind-9a13f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbq7R2xqQXkeCnSlxCXRo_fWPNElFavM8',
    appId: '1:141560742872:ios:6dc33f9832e9056d1228ad',
    messagingSenderId: '141560742872',
    projectId: 'hivemind-9a13f',
    storageBucket: 'hivemind-9a13f.firebasestorage.app',
    iosBundleId: 'com.example.hivemindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbq7R2xqQXkeCnSlxCXRo_fWPNElFavM8',
    appId: '1:141560742872:ios:6dc33f9832e9056d1228ad',
    messagingSenderId: '141560742872',
    projectId: 'hivemind-9a13f',
    storageBucket: 'hivemind-9a13f.firebasestorage.app',
    iosBundleId: 'com.example.hivemindApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVUk3UrAAqTLhVEiCmGe4NvCeDOuoXj50',
    appId: '1:141560742872:web:007b72cd98a9e1401228ad',
    messagingSenderId: '141560742872',
    projectId: 'hivemind-9a13f',
    authDomain: 'hivemind-9a13f.firebaseapp.com',
    storageBucket: 'hivemind-9a13f.firebasestorage.app',
  );
}
